# render.yaml
services:
  - type: web
    name: https://api.render.com/deploy/srv-d80b5d37uimc73fcnkcg?key=toUPQb5oQW8
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    initialDeployHook: ./seed_database.sh