services:
  - type: web
    name: vsulhs-sslg
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false       # ← set manually on Render dashboard
      - key: APP_URL
        value: https://my-thesisproject.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: vsulhs-sslg-db
          property: connectionString
    autoDeploy: true

databases:
  - name: vsulhs-sslg-db
    region: singapore
    plan: free