@extends('layouts.app')

@section('title', 'Financial Documents')

@section('content')
<div class="relative overflow-hidden rounded-2xl bg-gradient-to-r from-emerald-600 to-emerald-700 dark:from-emerald-800 dark:to-emerald-900 p-6 mb-6">
    <div class="relative z-10">
        <h1 class="text-2xl font-bold text-white">Financial Documents</h1>
        <p class="text-emerald-100 text-sm mt-1">Manage Income, Expense &amp; Receivable documents</p>
    </div>
    <div class="absolute top-0 right-0 -mt-8 -mr-8 w-64 h-64 bg-white/5 rounded-full blur-3xl"></div>
</div>

{{-- Flash Messages --}}
@if(session('success'))
    <div class="mb-4 p-4 bg-green-100 border border-green-300 text-green-800 rounded-xl text-sm">
        ✅ {{ session('success') }}
    </div>
@endif
@if(session('error'))
    <div class="mb-4 p-4 bg-red-100 border border-red-300 text-red-800 rounded-xl text-sm">
        ❌ {{ session('error') }}
    </div>
@endif

{{-- Filters + Action Buttons --}}
<div class="bg-white dark:bg-gray-800 rounded-2xl shadow border border-gray-200 dark:border-gray-700 p-4 mb-6">
    <div class="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">

        {{-- Left: Filter by category --}}
        <form method="GET" action="{{ route('documents.index') }}"
              class="flex flex-wrap gap-2 flex-1">
            <input type="text" name="search" value="{{ request('search') }}"
                   placeholder="Search title or description..."
                   class="flex-1 min-w-[180px] border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500">

            <select name="category" class="border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500">
                <option value="">All Categories</option>
                @foreach($categories as $cat)
                    <option value="{{ $cat->id }}" {{ request('category') == $cat->id ? 'selected' : '' }}>
                        {{ $cat->name }}
                    </option>
                @endforeach
            </select>

            {{-- Auto-generated filter --}}
            <select name="source" class="border border-gray-300 dark:border-gray-600 dark:bg-gray-700 dark:text-white rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500">
                <option value="">All Sources</option>
                <option value="auto"   {{ request('source') === 'auto'   ? 'selected' : '' }}>Auto-generated</option>
                <option value="manual" {{ request('source') === 'manual' ? 'selected' : '' }}>Manually uploaded</option>
            </select>

            <button type="submit"
                    class="bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-semibold px-4 py-2 rounded-lg transition whitespace-nowrap">
                Filter
            </button>
            <a href="{{ route('documents.index') }}"
               class="bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 text-sm font-semibold px-4 py-2 rounded-lg transition whitespace-nowrap">
                Reset
            </a>
        </form>

        {{-- Right: Trash + Upload --}}
        <div class="flex gap-2 flex-shrink-0">
            @if(Auth::user()->role->level === 1 || Auth::user()->hasPermission('documents.manage'))
                <a href="{{ route('documents.trash') }}"
                   class="inline-flex items-center gap-1.5 bg-gray-600 hover:bg-gray-700 text-white text-sm font-semibold px-3 py-2 rounded-lg transition">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                    </svg>
                    Trash
                </a>
            @endif
            @if(Auth::user()->role->level === 1 || Auth::user()->hasPermission('documents.create'))
                <a href="{{ route('documents.create') }}"
                   class="inline-flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-semibold px-3 py-2 rounded-lg transition">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
                    </svg>
                    Upload Document
                </a>
            @endif
        </div>

    </div>
</div>

{{-- Stats Row: show counts per financial category --}}
@if($autoGeneratedCount > 0)
<div class="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
    <div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-4 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-wider text-gray-400">All Documents</p>
        <p class="text-2xl font-bold text-gray-800 dark:text-white mt-1">{{ $totalCount }}</p>
    </div>
    <div class="bg-white dark:bg-gray-800 rounded-xl border border-emerald-200 dark:border-emerald-800 p-4 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-wider text-emerald-600 dark:text-emerald-400">Approved Income</p>
        <p class="text-2xl font-bold text-emerald-600 mt-1">{{ $incomeCount }}</p>
    </div>
    <div class="bg-white dark:bg-gray-800 rounded-xl border border-red-200 dark:border-red-800 p-4 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-wider text-red-500">Approved Expense</p>
        <p class="text-2xl font-bold text-red-500 mt-1">{{ $expenseCount }}</p>
    </div>
    <div class="bg-white dark:bg-gray-800 rounded-xl border border-purple-200 dark:border-purple-800 p-4 shadow-sm">
        <p class="text-xs font-semibold uppercase tracking-wider text-purple-600">Approved Receivable</p>
        <p class="text-2xl font-bold text-purple-600 mt-1">{{ $receivableCount }}</p>
    </div>
</div>
@endif

{{-- Documents Table --}}
<div class="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 overflow-hidden shadow-sm">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-emerald-600 dark:bg-emerald-800 text-white">
                <tr>
                    <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider">Title</th>
                    <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider">Category</th>
                    <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider">Source</th>
                    <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider">Uploaded By</th>
                    <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider">Size</th>
                    <th class="px-5 py-3 text-left text-xs font-semibold uppercase tracking-wider">Date</th>
                    <th class="px-5 py-3 text-right text-xs font-semibold uppercase tracking-wider">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-100 dark:divide-gray-700">
                @forelse($documents as $doc)
                @php
                    $version   = $doc->currentVersion;
                    $fileName  = $version?->file_name ?? '';
                    $ext       = strtolower(pathinfo($fileName, PATHINFO_EXTENSION));
                    $iconColor = match(true) {
                        $ext === 'pdf'                             => 'text-red-500',
                        in_array($ext, ['doc','docx'])             => 'text-blue-500',
                        in_array($ext, ['xls','xlsx'])             => 'text-green-600',
                        in_array($ext, ['ppt','pptx'])             => 'text-orange-500',
                        in_array($ext, ['jpg','jpeg','png','gif']) => 'text-purple-500',
                        $ext === 'zip'                             => 'text-yellow-600',
                        default                                    => 'text-gray-400',
                    };

                    // Detect auto-generated financial approval slips via tags
                    $tags        = $doc->tags ?? [];
                    $isAutoGen   = in_array('auto-generated', $tags);

                    // Category-based accent for auto-generated docs
                    $catName     = $doc->category?->name ?? '';
                    $accentClass = match(true) {
                        str_contains($catName, 'Income')     => 'border-l-4 border-emerald-400',
                        str_contains($catName, 'Expense')    => 'border-l-4 border-red-400',
                        str_contains($catName, 'Receivable') => 'border-l-4 border-purple-400',
                        default                              => '',
                    };
                @endphp
                <tr class="hover:bg-gray-50 dark:hover:bg-gray-700/50 transition {{ $isAutoGen ? 'bg-gray-50/50 dark:bg-gray-700/20' : '' }}">

                    {{-- Title --}}
                    <td class="px-5 py-3 font-medium max-w-xs {{ $accentClass }}">
                        <div class="flex items-center gap-2">
                            <span class="{{ $iconColor }} flex-shrink-0">
                                @if($ext === 'pdf')
                                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zm-1 1.5L18.5 9H13V3.5zM6 20V4h5v7h7v9H6z"/></svg>
                                @elseif(in_array($ext, ['doc','docx']))
                                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8l-6-6zm-1 1.5L18.5 9H13V3.5zM9 13h6v1H9v-1zm0 2h6v1H9v-1zm0 2h4v1H9v-1z"/></svg>
                                @elseif(in_array($ext, ['jpg','jpeg','png','gif']))
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"/></svg>
                                @else
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"/></svg>
                                @endif
                            </span>
                            <div class="min-w-0">
                                <a href="{{ route('documents.show', $doc) }}"
                                   class="text-emerald-600 dark:text-emerald-400 hover:underline block truncate max-w-[220px]"
                                   title="{{ $doc->title }}">
                                    {{ $doc->title }}
                                </a>
                                @if($doc->description)
                                    <p class="text-xs text-gray-400 truncate max-w-[220px]">{{ $doc->description }}</p>
                                @endif
                            </div>
                        </div>
                    </td>

                    {{-- Category --}}
                    <td class="px-5 py-3">
                        @if($doc->category)
                            @php
                                $badgeClass = match(true) {
                                    str_contains($catName, 'Income')     => 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-800 dark:text-emerald-300',
                                    str_contains($catName, 'Expense')    => 'bg-red-100 dark:bg-red-900/40 text-red-700 dark:text-red-300',
                                    str_contains($catName, 'Receivable') => 'bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300',
                                    default                              => 'bg-emerald-100 dark:bg-emerald-900/40 text-emerald-800 dark:text-emerald-300',
                                };
                            @endphp
                            <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium {{ $badgeClass }}">
                                {{ $doc->category->name }}
                            </span>
                        @else
                            <span class="text-gray-400">—</span>
                        @endif
                    </td>

                    {{-- Source: Auto-generated vs Manual --}}
                    <td class="px-5 py-3">
                        @if($isAutoGen)
                            <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300"
                                  title="Auto-saved when transaction was approved">
                                <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/>
                                </svg>
                                Auto
                            </span>
                        @else
                            <span class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400">
                                <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"/>
                                </svg>
                                Manual
                            </span>
                        @endif
                    </td>

                    {{-- Uploaded By --}}
                    <td class="px-5 py-3 text-gray-600 dark:text-gray-400">
                        {{ $doc->owner->full_name ?? 'System' }}
                    </td>

                    {{-- Size --}}
                    <td class="px-5 py-3 text-gray-500 dark:text-gray-400 text-xs font-mono">
                        {{ $doc->formatted_size }}
                    </td>

                    {{-- Date --}}
                    <td class="px-5 py-3 text-gray-500 dark:text-gray-400 text-xs whitespace-nowrap">
                        {{ $doc->created_at->format('M d, Y') }}
                    </td>

                    {{-- Actions --}}
                    <td class="px-5 py-3 text-right">
                        <div class="flex items-center justify-end gap-1">

                            {{-- Preview (PDF / image only) --}}
                            @if($version && in_array($ext, ['pdf','jpg','jpeg','png','gif']))
                            <button onclick="openPreview(
                                '{{ route('documents.preview', $doc) }}',
                                '{{ route('documents.download', $doc) }}',
                                {{ json_encode($doc->title) }},
                                '{{ $ext }}'
                            )" class="p-1.5 text-gray-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
                               title="Preview">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                                </svg>
                            </button>
                            @endif

                            {{-- Download --}}
                            @if($version)
                            <a href="{{ route('documents.download', $doc) }}"
                               class="p-1.5 text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 transition rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
                               title="Download">
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
                                </svg>
                            </a>
                            @else
                            <span class="text-xs text-gray-400 px-2">—</span>
                            @endif

                            {{-- Edit: blocked for auto-generated docs --}}
                            @if(Auth::user()->role->level === 1 || Auth::user()->hasPermission('documents.edit'))
                                @if($isAutoGen)
                                    <span class="p-1.5 text-gray-200 dark:text-gray-600 cursor-not-allowed rounded-lg"
                                          title="Auto-generated documents cannot be edited">
                                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
                                        </svg>
                                    </span>
                                @else
                                    <a href="{{ route('documents.edit', $doc) }}"
                                       class="p-1.5 text-gray-400 hover:text-emerald-600 dark:hover:text-emerald-400 transition rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
                                       title="Edit">
                                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
                                        </svg>
                                    </a>
                                @endif
                            @endif

                            {{-- Delete --}}
                            @if(Auth::user()->role->level === 1 || Auth::user()->hasPermission('documents.delete'))
                            <form method="POST" action="{{ route('documents.destroy', $doc) }}"
                                  onsubmit="return confirm('{{ $isAutoGen ? 'This is an auto-generated approval record. Delete anyway?' : 'Delete this document?' }}')"
                                  class="inline">
                                @csrf @method('DELETE')
                                <button type="submit"
                                    class="p-1.5 text-gray-400 hover:text-red-600 dark:hover:text-red-400 transition rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700"
                                    title="Delete">
                                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                                    </svg>
                                </button>
                            </form>
                            @endif

                        </div>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="px-5 py-12 text-center">
                        <div class="flex flex-col items-center gap-3">
                            <svg class="w-16 h-16 text-gray-300 dark:text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                            </svg>
                            <p class="text-gray-500 dark:text-gray-400">No documents found.</p>
                            @if(Auth::user()->role->level === 1 || Auth::user()->hasPermission('documents.create'))
                                <a href="{{ route('documents.create') }}" class="text-emerald-600 hover:underline text-sm">Upload your first document</a>
                            @endif
                        </div>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    @if($documents->hasPages())
    <div class="px-5 py-3 border-t border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
        {{ $documents->links() }}
    </div>
    @endif
</div>

{{-- Preview Modal (unchanged from original) --}}
<div id="preview-modal" class="fixed inset-0 z-50 hidden items-center justify-center p-4"
     style="background:rgba(0,0,0,0.7)"
     aria-modal="true" role="dialog" aria-label="Document preview">
    <div class="relative bg-white dark:bg-gray-900 rounded-2xl shadow-2xl w-full max-w-4xl max-h-[90vh] flex flex-col overflow-hidden">
        <div class="flex items-center justify-between px-5 py-3 border-b border-gray-200 dark:border-gray-700 flex-shrink-0">
            <h3 id="preview-title" class="text-sm font-semibold text-gray-800 dark:text-white truncate max-w-md"></h3>
            <div class="flex items-center gap-2">
                <a id="preview-download-link" href="#"
                   class="inline-flex items-center gap-1 text-xs bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-1 rounded-lg transition">
                    <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"/>
                    </svg>
                    Download
                </a>
                <button onclick="closePreview()"
                        class="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition text-xl leading-none">&times;</button>
            </div>
        </div>
        <div class="flex-1 overflow-auto flex items-center justify-center p-4 min-h-0">
            <iframe id="preview-iframe" src="" class="hidden w-full rounded-lg border border-gray-200 dark:border-gray-700" style="height:70vh" title="PDF preview"></iframe>
            <img id="preview-img" src="" alt="Document preview" class="hidden max-w-full max-h-full rounded-lg object-contain">
            <p id="preview-unsupported" class="hidden text-gray-500 dark:text-gray-400 text-sm">Preview not available for this file type.</p>
        </div>
    </div>
</div>

<script>
function openPreview(previewUrl, downloadUrl, title, ext) {
    document.getElementById('preview-title').textContent = title;
    document.getElementById('preview-download-link').href = downloadUrl;
    const iframe = document.getElementById('preview-iframe');
    const img    = document.getElementById('preview-img');
    const unsup  = document.getElementById('preview-unsupported');
    iframe.classList.add('hidden'); iframe.src = '';
    img.classList.add('hidden');    img.src    = '';
    unsup.classList.add('hidden');
    const imageExts = ['jpg','jpeg','png','gif','webp'];
    if (ext === 'pdf') {
        iframe.src = previewUrl;
        iframe.classList.remove('hidden');
    } else if (imageExts.includes(ext)) {
        img.src = previewUrl;
        img.classList.remove('hidden');
    } else {
        unsup.classList.remove('hidden');
    }
    const modal = document.getElementById('preview-modal');
    modal.style.display = 'flex';
    document.body.style.overflow = 'hidden';
}
function closePreview() {
    document.getElementById('preview-modal').style.display = 'none';
    document.getElementById('preview-iframe').src = '';
    document.getElementById('preview-img').src    = '';
    document.body.style.overflow = '';
}
document.getElementById('preview-modal').addEventListener('click', function(e) {
    if (e.target === this) closePreview();
});
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') closePreview();
});
</script>
@endsection