<?php

namespace App\Http\Controllers;

use App\Models\Document;
use App\Models\DocumentCategory;
use App\Services\AuditLogger;
use App\Services\CloudinaryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class DocumentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth.custom');
    }

    // -------------------------------------------------------------------------
    // Index
    // -------------------------------------------------------------------------

    public function index(Request $request)
    {
        $isPostgres = DB::getDriverName() === 'pgsql';

        $incomeCategory     = DocumentCategory::where('name', 'Approved Income')->first();
        $expenseCategory    = DocumentCategory::where('name', 'Approved Expense')->first();
        $receivableCategory = DocumentCategory::where('name', 'Approved Receivable')->first();

        $query = $this->applyDocumentFilters(
            Document::with([
                'currentVersion:id,document_id,file_path,file_size,created_at',
                'owner:id,first_name,middle_name,last_name',
                'category:id,name'
            ])->latest(),
            $request
        );

        $documents  = $query->paginate(15)->appends($request->except('page'));
        $categories = DocumentCategory::select('id', 'name')->orderBy('name')->get();

        $autoExpr = $isPostgres
            ? "tags::jsonb @> '[\"auto-generated\"]'::jsonb"
            : "JSON_CONTAINS(tags, '[\"auto-generated\"]')";

        $statsQuery = $this->applyDocumentFilters(Document::query(), $request);
        $baseQuery  = $statsQuery->selectRaw("
            COUNT(CASE WHEN $autoExpr THEN 1 END) as auto_count,
            COUNT(*) as total_count,
            COUNT(CASE WHEN document_category_id = ? THEN 1 END) as income_count,
            COUNT(CASE WHEN document_category_id = ? THEN 1 END) as expense_count,
            COUNT(CASE WHEN document_category_id = ? THEN 1 END) as receivable_count
        ", [
            $incomeCategory?->id,
            $expenseCategory?->id,
            $receivableCategory?->id,
        ])->first();

        $autoGeneratedCount = $baseQuery->auto_count       ?? 0;
        $totalCount         = $baseQuery->total_count      ?? 0;
        $incomeCount        = $baseQuery->income_count     ?? 0;
        $expenseCount       = $baseQuery->expense_count    ?? 0;
        $receivableCount    = $baseQuery->receivable_count ?? 0;

        return view('documents.index', compact(
            'documents', 'categories',
            'autoGeneratedCount', 'totalCount',
            'incomeCount', 'expenseCount', 'receivableCount'
        ));
    }

    // -------------------------------------------------------------------------
    // Helper Methods
    // -------------------------------------------------------------------------

    private function applyDocumentFilters($query, Request $request)
    {
        $isPostgres = DB::getDriverName() === 'pgsql';

        if ($request->filled('search')) {
            $query->where(function ($q) use ($request) {
                $q->where('title', 'like', '%' . $request->search . '%')
                    ->orWhere('description', 'like', '%' . $request->search . '%');
            });
        }

        if ($request->filled('category')) {
            $query->where('document_category_id', $request->category);
        }

        if ($request->filled('source')) {
            if ($request->source === 'auto') {
                $query->whereJsonContains('tags', 'auto-generated');
            } elseif ($request->source === 'manual') {
                if ($isPostgres) {
                    $query->where(function ($q) {
                        $q->whereNull('tags')
                            ->orWhereRaw("NOT (tags::jsonb @> '[\"auto-generated\"]'::jsonb)");
                    });
                } else {
                    $query->where(function ($q) {
                        $q->whereNull('tags')
                            ->orWhereRaw("JSON_SEARCH(tags, 'one', 'auto-generated') IS NULL");
                    });
                }
            }
        }

        return $query;
    }

    // -------------------------------------------------------------------------
    // Show
    // -------------------------------------------------------------------------

    public function show(Document $document)
    {
        $this->authorize('view', $document);

        return view('documents.show', compact('document'));
    }

    // -------------------------------------------------------------------------
    // Create / Store
    // -------------------------------------------------------------------------

    public function create()
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && ! $user->hasPermission('documents.create')) {
            abort(403);
        }

        $categories = DocumentCategory::active()->orderBy('name')->get(['id', 'name']);

        return view('documents.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && ! $user->hasPermission('documents.create')) {
            abort(403);
        }

        $validated = $request->validate([
            'title'                => 'required|string|max:255',
            'description'          => 'nullable|string',
            'document_category_id' => 'nullable|exists:document_categories,id',
            'tags'                 => 'nullable|string|max:255',
            'change_notes'         => 'nullable|string',
            'file'                 => 'required|file|max:10240|mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip',
        ]);

        $tagsArray = [];
        if (! empty($validated['tags'])) {
            $tagsArray = array_map('trim', explode(',', $validated['tags']));
        }

        // ✅ Upload to Cloudinary
        $cloudinary = new CloudinaryService();
        $uploaded   = $cloudinary->upload($request->file('file'));

        $document = Document::create([
            'title'                => $validated['title'],
            'description'          => $validated['description'] ?? null,
            'document_category_id' => $validated['document_category_id'] ?? null,
            'tags'                 => $tagsArray,
            'owner_id'             => $user->id,
            'current_version_id'   => null,
            'uploaded_at'          => now(),
        ]);

        // ✅ Pass Cloudinary URL to addVersion
        $version = $document->addVersion(
            $uploaded['url'],
            $uploaded['public_id'],
            $validated['change_notes'] ?? 'Initial upload',
            $request->file('file')->getSize(),
            $request->file('file')->getClientOriginalName(),
            $request->file('file')->getMimeType(),
        );

        if (! $document->current_version_id && $version) {
            $document->current_version_id = $version->id;
            $document->saveQuietly();
        }

        AuditLogger::log('created', $document, "Document: {$document->title}");

        return redirect()->route('documents.index')
            ->with('success', 'Document uploaded successfully.');
    }

    // -------------------------------------------------------------------------
    // Edit / Update
    // -------------------------------------------------------------------------

    public function edit(Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && ! $user->hasPermission('documents.edit')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403, 'You can only edit your own documents.');
        }

        $categories = DocumentCategory::active()->orderBy('name')->get(['id', 'name']);

        return view('documents.edit', compact('document', 'categories'));
    }

    public function update(Request $request, Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && ! $user->hasPermission('documents.edit')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403);
        }

        $validated = $request->validate([
            'title'                => 'required|string|max:255',
            'description'          => 'nullable|string',
            'document_category_id' => 'nullable|exists:document_categories,id',
        ]);

        $oldData = $document->getOriginal();
        $document->update($validated);

        if ($request->hasFile('file')) {
            $request->validate([
                'file' => 'file|max:20480|mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip',
            ]);

            $cloudinary = new CloudinaryService();

            // ✅ Delete old file from Cloudinary
            if ($document->currentVersion?->cloudinary_public_id) {
                $cloudinary->delete($document->currentVersion->cloudinary_public_id);
            }

            // ✅ Upload new file to Cloudinary
            $uploaded = $cloudinary->upload($request->file('file'));

            $document->addVersion(
                $uploaded['url'],
                $uploaded['public_id'],
                $request->input('change_notes', 'Updated document'),
                $request->file('file')->getSize(),
                $request->file('file')->getClientOriginalName(),
                $request->file('file')->getMimeType(),
            );
        }

        AuditLogger::log('updated', $document, "Document: {$document->title}", $oldData, $document->getChanges());

        return redirect()->route('documents.index')
            ->with('success', 'Document updated successfully.');
    }

    // -------------------------------------------------------------------------
    // Destroy
    // -------------------------------------------------------------------------

    public function destroy(Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && ! $user->hasPermission('documents.delete')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403);
        }

        $tags = is_array($document->tags) ? $document->tags : ($document->tags ?? []);
        if (in_array('auto-generated', $tags)) {
            return redirect()->route('documents.index')
                ->with('error', 'Auto-generated financial documents cannot be deleted here. To remove this record and keep your totals accurate, delete the transaction directly from Financial Records.');
        }

        AuditLogger::log('deleted', $document, "Document: {$document->title}", $document->toArray(), []);
        $document->delete();

        return redirect()->route('documents.index')
            ->with('success', 'Document deleted successfully.');
    }

    // -------------------------------------------------------------------------
    // Download / Preview — public Cloudinary URL
    // -------------------------------------------------------------------------

    public function download(Document $document)
    {
        $this->authorize('view', $document);

        if (! $document->currentVersion?->file_path) {
            return redirect()->back()->with('error', 'No file available for this document.');
        }

        // ✅ Redirect to public Cloudinary URL
        return redirect($document->currentVersion->file_path);
    }

    public function preview(Document $document)
    {
        $this->authorize('view', $document);

        if (! $document->currentVersion?->file_path) {
            abort(404);
        }

        // ✅ Redirect to public Cloudinary URL
        return redirect($document->currentVersion->file_path);
    }

    // -------------------------------------------------------------------------
    // Trash / Restore / Force Delete
    // -------------------------------------------------------------------------

    public function trash()
    {
        if (! Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $documents = Document::onlyTrashed()
            ->with(['owner', 'currentVersion', 'category'])
            ->latest('deleted_at')
            ->paginate(15);

        return view('documents.trash', compact('documents'));
    }

    public function restore($id)
    {
        if (! Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $document = Document::onlyTrashed()->findOrFail($id);
        $document->restore();

        AuditLogger::log('restored', $document, "Document: {$document->title}");

        return redirect()->route('documents.trash')
            ->with('success', 'Document restored successfully.');
    }

    public function forceDelete($id)
    {
        if (! Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $document = Document::onlyTrashed()->with('versions')->findOrFail($id);

        $tags = is_array($document->tags) ? $document->tags : ($document->tags ?? []);
        if (in_array('auto-generated', $tags)) {
            return redirect()->route('documents.trash')
                ->with('error', 'Auto-generated financial documents must be removed via Financial Records.');
        }

        AuditLogger::log('force_deleted', $document, "Document: {$document->title}", $document->toArray(), []);

        $cloudinary = new CloudinaryService();

        DB::transaction(function () use ($document, $cloudinary) {
            // ✅ Delete all versions from Cloudinary
            foreach ($document->versions as $version) {
                if ($version->cloudinary_public_id) {
                    $cloudinary->delete($version->cloudinary_public_id);
                }
            }

            $document->versions()->delete();

            DB::table('attachments')
                ->where('attachable_type', Document::class)
                ->where('document_id', $document->id)
                ->delete();

            $document->forceDelete();
        });

        return redirect()->route('documents.trash')
            ->with('success', 'Document and all its files permanently deleted.');
    }
}