<?php

namespace App\Http\Controllers;

use App\Models\Document;
use App\Models\DocumentCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Services\AuditLogger;

class DocumentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth.custom');
    }

    // -------------------------------------------------------------------------
    // Index – all documents are public, no visibility filtering
    // -------------------------------------------------------------------------

    public function index(Request $request)
    {
        $query = Document::with(['currentVersion:id,document_id,file_path,created_at', 'owner:id,full_name', 'category:id,name'])->latest();

        // Search
        if ($request->filled('search')) {
            $query->where(function ($q) use ($request) {
                $q->where('title', 'like', '%' . $request->search . '%')
                  ->orWhere('description', 'like', '%' . $request->search . '%');
            });
        }

        // Filter by category
        if ($request->filled('category')) {
            $query->where('document_category_id', $request->category);
        }

        // Filter by source: auto-generated (has 'auto-generated' tag) vs manual
        if ($request->filled('source')) {
            if ($request->source === 'auto') {
                $query->whereJsonContains('tags', 'auto-generated');
            } elseif ($request->source === 'manual') {
                $query->where(function ($q) {
                    $q->whereNull('tags')
                      ->orWhereRaw("JSON_SEARCH(tags, 'one', 'auto-generated') IS NULL");
                });
            }
        }

        $documents = $query->paginate(15)->appends($request->except('page'));

        // Categories for filter dropdown
        $categories = DocumentCategory::select('id', 'name')->orderBy('name')->get();

        // Counts for the stats row - use single query with conditional counting
        $baseQuery = Document::selectRaw('
            COUNT(CASE WHEN JSON_CONTAINS(tags, \'["auto-generated"]\') THEN 1 END) as auto_count,
            COUNT(*) as total_count,
            COUNT(CASE WHEN document_category_id = (SELECT id FROM document_categories WHERE name = "Approved Income") THEN 1 END) as income_count,
            COUNT(CASE WHEN document_category_id = (SELECT id FROM document_categories WHERE name = "Approved Expense") THEN 1 END) as expense_count,
            COUNT(CASE WHEN document_category_id = (SELECT id FROM document_categories WHERE name = "Approved Receivable") THEN 1 END) as receivable_count
        ')->first();
        
        $autoGeneratedCount = $baseQuery->auto_count ?? 0;
        $totalCount = $baseQuery->total_count ?? 0;
        $incomeCount = $baseQuery->income_count ?? 0;
        $expenseCount = $baseQuery->expense_count ?? 0;
        $receivableCount = $baseQuery->receivable_count ?? 0;

        return view('documents.index', compact(
            'documents', 'categories',
            'autoGeneratedCount', 'totalCount',
            'incomeCount', 'expenseCount', 'receivableCount'
        ));
    }

    // -------------------------------------------------------------------------
    // Show – policy handles access
    // -------------------------------------------------------------------------

    public function show(Document $document)
    {
        $this->authorize('view', $document);
        return view('documents.show', compact('document'));
    }

    // -------------------------------------------------------------------------
    // Create – no category for manual uploads
    // -------------------------------------------------------------------------

    public function create()
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.create')) {
            abort(403);
        }

        // No categories passed – manual uploads have document_category_id = null
        return view('documents.create');
    }

    // -------------------------------------------------------------------------
    // Store – handles manual file upload, no category
    // -------------------------------------------------------------------------

    public function store(Request $request)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.create')) {
            abort(403);
        }

        $validated = $request->validate([
            'title'        => 'required|string|max:255',
            'description'  => 'nullable|string',
            'tags'         => 'nullable|string|max:255',       // comma-separated
            'change_notes' => 'nullable|string',
            'file'         => 'required|file|max:10240|mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip',
        ]);

        // Convert comma-separated tags to array
        $tagsArray = [];
        if (!empty($validated['tags'])) {
            $tagsArray = array_map('trim', explode(',', $validated['tags']));
        }

        // Create document with no category (document_category_id = null)
        $document = Document::create([
            'title'                => $validated['title'],
            'description'          => $validated['description'] ?? null,
            'document_category_id' => null,                 // manual uploads have no category
            'tags'                 => $tagsArray,
            'owner_id'             => $user->id,
            'current_version_id'   => null,                 // will be set after version is added
        ]);

        // Add the first version (the file)
        $version = $document->addVersion(
            $request->file('file'),
            $validated['change_notes'] ?? 'Initial upload'
        );

        // Ensure the document points to the current version
        if (!$document->current_version_id && $version) {
            $document->current_version_id = $version->id;
            $document->saveQuietly();
        }

        AuditLogger::log('created', $document, "Document: {$document->title}");

        return redirect()->route('documents.index')
            ->with('success', 'Document uploaded successfully.');
    }

    // -------------------------------------------------------------------------
    // Edit / Update – using document_category_id (only for existing categories)
    // -------------------------------------------------------------------------

    public function edit(Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.edit')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403, 'You can only edit your own documents.');
        }

        // Only fetch categories if the document already has one (auto-generated documents)
        // For manual uploads, the category dropdown is empty anyway.
        $categories = DocumentCategory::active()->orderBy('name')->pluck('name', 'id');
        return view('documents.edit', compact('document', 'categories'));
    }

    public function update(Request $request, Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.edit')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403);
        }

        $validated = $request->validate([
            'title'         => 'required|string|max:255',
            'description'   => 'nullable|string',
            'document_category_id' => 'nullable|exists:document_categories,id',
        ]);

        $oldData = $document->getOriginal();
        $document->update($validated);

        if ($request->hasFile('file')) {
            $request->validate([
                'file' => 'file|max:20480|mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip',
            ]);
            $document->addVersion($request->file('file'), $request->input('change_notes', 'Updated document'));
        }

        AuditLogger::log('updated', $document, "Document: {$document->title}", $oldData, $document->getChanges());

        return redirect()->route('documents.index')
            ->with('success', 'Document updated successfully.');
    }

    // -------------------------------------------------------------------------
    // Destroy – permission based
    // -------------------------------------------------------------------------

    public function destroy(Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.delete')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403);
        }

        AuditLogger::log('deleted', $document, "Document: {$document->title}", $document->toArray(), []);

        $document->delete();

        return redirect()->route('documents.index')
            ->with('success', 'Document deleted successfully.');
    }

    // -------------------------------------------------------------------------
    // Download / Preview – policy handles access
    // -------------------------------------------------------------------------

    public function download(Document $document)
    {
        $this->authorize('view', $document);

        if (!$document->currentVersion) {
            return redirect()->back()->with('error', 'No file available for this document.');
        }

        $version = $document->currentVersion;
        $path = $version->file_path;

        if (!Storage::disk('private')->exists($path)) {
            return redirect()->back()->with('error', 'File not found on server. Please contact administrator.');
        }

        return Storage::disk('private')->download($path, $version->file_name);
    }

    public function preview(Document $document)
    {
        $this->authorize('view', $document);

        if (!$document->currentVersion) {
            abort(404);
        }

        $version = $document->currentVersion;
        $path = $version->file_path;

        if (!Storage::disk('private')->exists($path)) {
            abort(404);
        }

        return response()->file(Storage::disk('private')->path($path), [
            'Content-Type' => $version->mime_type,
        ]);
    }

    // -------------------------------------------------------------------------
    // Trash / Restore / Force Delete – permission based
    // -------------------------------------------------------------------------

    public function trash()
    {
        if (!Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }
 
        $documents = Document::onlyTrashed()
            ->with(['owner', 'currentVersion', 'category'])
            ->latest('deleted_at')
            ->paginate(15);
 
        return view('documents.trash', compact('documents'));
    }

    public function restore($id)
    {
        if (!Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $document = Document::onlyTrashed()->findOrFail($id);
        $document->restore();

        AuditLogger::log('restored', $document, "Document: {$document->title}");

        return redirect()->route('documents.trash')
            ->with('success', 'Document restored successfully.');
    }

    public function forceDelete($id)
    {
        if (!Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $document = Document::onlyTrashed()->findOrFail($id);

        AuditLogger::log('force_deleted', $document, "Document: {$document->title}", $document->toArray(), []);

        $document->forceDelete();

        return redirect()->route('documents.trash')
            ->with('success', 'Document permanently deleted.');
    }
}