<?php

namespace App\Http\Controllers;

use App\Models\Document;
use App\Models\DocumentCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Services\AuditLogger;

class DocumentController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth.custom');
    }

    // -------------------------------------------------------------------------
    // Index
    // -------------------------------------------------------------------------

    public function index(Request $request)
    {
        $query = Document::with(['currentVersion:id,document_id,file_path,created_at', 'owner:id,full_name', 'category:id,name'])->latest();

        if ($request->filled('search')) {
            $query->where(function ($q) use ($request) {
                $q->where('title', 'like', '%' . $request->search . '%')
                  ->orWhere('description', 'like', '%' . $request->search . '%');
            });
        }

        if ($request->filled('category')) {
            $query->where('document_category_id', $request->category);
        }

        if ($request->filled('source')) {
            if ($request->source === 'auto') {
                $query->whereJsonContains('tags', 'auto-generated');
            } elseif ($request->source === 'manual') {
                $query->where(function ($q) {
                    $q->whereNull('tags')
                      ->orWhereRaw("JSON_SEARCH(tags, 'one', 'auto-generated') IS NULL");
                });
            }
        }

        $documents  = $query->paginate(15)->appends($request->except('page'));
        $categories = DocumentCategory::select('id', 'name')->orderBy('name')->get();

        $baseQuery = Document::selectRaw('
            COUNT(CASE WHEN JSON_CONTAINS(tags, \'["auto-generated"]\') THEN 1 END) as auto_count,
            COUNT(*) as total_count,
            COUNT(CASE WHEN document_category_id = (SELECT id FROM document_categories WHERE name = "Approved Income") THEN 1 END) as income_count,
            COUNT(CASE WHEN document_category_id = (SELECT id FROM document_categories WHERE name = "Approved Expense") THEN 1 END) as expense_count,
            COUNT(CASE WHEN document_category_id = (SELECT id FROM document_categories WHERE name = "Approved Receivable") THEN 1 END) as receivable_count
        ')->first();

        $autoGeneratedCount = $baseQuery->auto_count ?? 0;
        $totalCount         = $baseQuery->total_count ?? 0;
        $incomeCount        = $baseQuery->income_count ?? 0;
        $expenseCount       = $baseQuery->expense_count ?? 0;
        $receivableCount    = $baseQuery->receivable_count ?? 0;

        return view('documents.index', compact(
            'documents', 'categories',
            'autoGeneratedCount', 'totalCount',
            'incomeCount', 'expenseCount', 'receivableCount'
        ));
    }

    // -------------------------------------------------------------------------
    // Show
    // -------------------------------------------------------------------------

    public function show(Document $document)
    {
        $this->authorize('view', $document);
        return view('documents.show', compact('document'));
    }

    // -------------------------------------------------------------------------
    // Create / Store
    // -------------------------------------------------------------------------

    public function create()
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.create')) {
            abort(403);
        }
        return view('documents.create');
    }

    public function store(Request $request)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.create')) {
            abort(403);
        }

        $validated = $request->validate([
            'title'        => 'required|string|max:255',
            'description'  => 'nullable|string',
            'tags'         => 'nullable|string|max:255',
            'change_notes' => 'nullable|string',
            'file'         => 'required|file|max:10240|mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip',
        ]);

        $tagsArray = [];
        if (!empty($validated['tags'])) {
            $tagsArray = array_map('trim', explode(',', $validated['tags']));
        }

        $document = Document::create([
            'title'                => $validated['title'],
            'description'          => $validated['description'] ?? null,
            'document_category_id' => null,
            'tags'                 => $tagsArray,
            'owner_id'             => $user->id,
            'current_version_id'   => null,
        ]);

        $version = $document->addVersion(
            $request->file('file'),
            $validated['change_notes'] ?? 'Initial upload'
        );

        if (!$document->current_version_id && $version) {
            $document->current_version_id = $version->id;
            $document->saveQuietly();
        }

        AuditLogger::log('created', $document, "Document: {$document->title}");

        return redirect()->route('documents.index')
            ->with('success', 'Document uploaded successfully.');
    }

    // -------------------------------------------------------------------------
    // Edit / Update
    // -------------------------------------------------------------------------

    public function edit(Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.edit')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403, 'You can only edit your own documents.');
        }

        $categories = DocumentCategory::active()->orderBy('name')->pluck('name', 'id');
        return view('documents.edit', compact('document', 'categories'));
    }

    public function update(Request $request, Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.edit')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403);
        }

        $validated = $request->validate([
            'title'                => 'required|string|max:255',
            'description'          => 'nullable|string',
            'document_category_id' => 'nullable|exists:document_categories,id',
        ]);

        $oldData = $document->getOriginal();
        $document->update($validated);

        if ($request->hasFile('file')) {
            $request->validate([
                'file' => 'file|max:20480|mimes:pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,zip',
            ]);
            $document->addVersion($request->file('file'), $request->input('change_notes', 'Updated document'));
        }

        AuditLogger::log('updated', $document, "Document: {$document->title}", $oldData, $document->getChanges());

        return redirect()->route('documents.index')
            ->with('success', 'Document updated successfully.');
    }

    // -------------------------------------------------------------------------
    // Destroy — blocks auto-generated financial documents
    // -------------------------------------------------------------------------

    public function destroy(Document $document)
    {
        $user = Auth::user();
        if ($user->role->level !== 1 && !$user->hasPermission('documents.delete')) {
            abort(403);
        }
        if ($user->role->level !== 1 && $document->owner_id !== $user->id) {
            abort(403);
        }

        // Block deletion of auto-generated financial approval slips.
        // Deleting the document alone removes the file but leaves the financial
        // transaction intact — it would keep counting toward income/expense totals.
        // The correct flow is to delete from Financial Records, which soft-deletes
        // the transaction (removing it from all totals) and its linked documents together.
        $tags = is_array($document->tags) ? $document->tags : ($document->tags ?? []);
        if (in_array('auto-generated', $tags)) {
            return redirect()->route('documents.index')
                ->with('error', 'Auto-generated financial documents cannot be deleted here. To remove this record and keep your totals accurate, delete the transaction directly from Financial Records.');
        }

        AuditLogger::log('deleted', $document, "Document: {$document->title}", $document->toArray(), []);

        $document->delete();

        return redirect()->route('documents.index')
            ->with('success', 'Document deleted successfully.');
    }

    // -------------------------------------------------------------------------
    // Download / Preview
    // -------------------------------------------------------------------------

    public function download(Document $document)
    {
        $this->authorize('view', $document);

        if (!$document->currentVersion) {
            return redirect()->back()->with('error', 'No file available for this document.');
        }

        $version = $document->currentVersion;
        $path    = $version->file_path;

        if (!Storage::disk('private')->exists($path)) {
            return redirect()->back()->with('error', 'File not found on server. Please contact administrator.');
        }

        return Storage::disk('private')->download($path, $version->file_name);
    }

    public function preview(Document $document)
    {
        $this->authorize('view', $document);

        if (!$document->currentVersion) abort(404);

        $version = $document->currentVersion;
        $path    = $version->file_path;

        if (!Storage::disk('private')->exists($path)) abort(404);

        return response()->file(Storage::disk('private')->path($path), [
            'Content-Type' => $version->mime_type,
        ]);
    }

    // -------------------------------------------------------------------------
    // Trash / Restore / Force Delete
    // -------------------------------------------------------------------------

    public function trash()
    {
        if (!Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $documents = Document::onlyTrashed()
            ->with(['owner', 'currentVersion', 'category'])
            ->latest('deleted_at')
            ->paginate(15);

        return view('documents.trash', compact('documents'));
    }

    public function restore($id)
    {
        if (!Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $document = Document::onlyTrashed()->findOrFail($id);
        $document->restore();

        AuditLogger::log('restored', $document, "Document: {$document->title}");

        return redirect()->route('documents.trash')
            ->with('success', 'Document restored successfully.');
    }

    public function forceDelete($id)
    {
        if (!Auth::user()->hasPermission('documents.manage') && Auth::user()->role->level !== 1) {
            abort(403);
        }

        $document = Document::onlyTrashed()->with('versions')->findOrFail($id);

        // Block force-delete of auto-generated financial docs
        $tags = is_array($document->tags) ? $document->tags : ($document->tags ?? []);
        if (in_array('auto-generated', $tags)) {
            return redirect()->route('documents.trash')
                ->with('error', 'Auto-generated financial documents must be removed via Financial Records to keep totals accurate.');
        }

        AuditLogger::log('force_deleted', $document, "Document: {$document->title}", $document->toArray(), []);

        DB::transaction(function () use ($document) {
            // 1. Delete every physical file from disk
            foreach ($document->versions as $version) {
                if ($version->file_path && Storage::disk('private')->exists($version->file_path)) {
                    Storage::disk('private')->delete($version->file_path);
                }
            }

            // 2. Delete all version records from DB
            $document->versions()->delete();

            // 3. Detach from any pivot tables (attachments)
            DB::table('attachments')
                ->where('attachable_type', Document::class)
                ->where('document_id', $document->id)
                ->delete();

            // 4. Permanently delete the document record
            $document->forceDelete();
        });

        return redirect()->route('documents.trash')
            ->with('success', 'Document and all its files permanently deleted.');
    }
}